language: ruby
rvm:
- 2.4.1

before_install:
  - chmod +x bin/cibuild

script: "./bin/cibuild"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
cache: bundler
notifications:
  email: false
