title:             ProITC Solution
email:             juan.moreno@proitcsolution.com.ve
description:       ProITC Solution
author:            Juan Moreno
url:               "https://proitcsolution.com.ve"
name:              ProITC Solution

# Social Profiles
twitter_username:  juan_shoko
github_username:   earth001

# Build settings
markdown:          kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
