title:             ProITC Solution
email:             juan.moreno@proitcsolution.com.ve
description:       ProITC Solution | Java, Spring, Best Practices and Web Development
author:            Juan Moreno
#baseurl:		   "/"
url:               "https://proitcsolution.com.ve"
name:              ProITC Solution

# Social Profiles
twitter_username:  juan_shoko
github_username:   earth001
facebook_username:  
linkedin_username:
stackoverflow_username: 4825845
# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-144979526-1 # out your google-analytics code

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
