title:             ProITC Solution
email:             jmoreno@proitcsolution.com.ve
description:       Java | Best Practices and Software Development
author:            Juan Moreno
#baseurl:		   "/"
url:               "https://proitcsolution.com.ve"
name:              ProITC Solution

# Social Profiles
twitter_username:  JuanMorenoDev
github_username:   JuanMorenoDeveloper
facebook_username:  
linkedin_username: juanantoniomorenoortega
stackoverflow_username: 4825845
# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-144979526-1 # out your google-analytics code

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
exclude:
  - .idea
  - vendor